# experiments log
experiment_name : 'exp02_kalmanGRU'
trial_name : '03'
epoch : 3000
checkpoint_name : 'KalmanNet_train_89502.81069987721_epoch_10.pt'

# deep model
model_name: 'KalmanNet'
target_state_dim : 6
measurement_dim : 3
in_mult : 50
out_mult : 10

# ss model
observation_noise : 1000
init_state_mean : [[10000], [100000], [0], [0], [0], [0]]
init_state_covariance_scaling : 1

# KG model
kalman_gain_model : 'EKF'

# train method
learning_rate : 0.1
batch_size : 32
optimizer_name: Adam
backward_sequence_length : 150
use_scheduler: true
scheduler_name : 'ReduceLROnPlateau'

# save checkpoints
save_every_epoch : 10

# dataset
dataset:
  train : 'data/processed/train_3800.pt'