# experiments log
experiment_name : 'exp01_kalmanNet'
trial_name : '01'

# model
model_name: 'KalmanNet'
target_state_dim : 6
measurement_dim : 3
in_mult : 5
out_mult : 50


batch_size : 4

optimizer_name: SGD

dataset:
  cv : 'data/processed/cv'