# experiments log
experiment_name : 'exp01_kalmanNet'
trial_name : '02'
epoch : 3000
checkpoint_name : 'KalmanNet_train_1.5814213848429706_epoch_2500.pt'

# deep model
model_name: 'KalmanNet'
target_state_dim : 6
measurement_dim : 3
in_mult : 20
out_mult : 60

# ssmodel
observation_noise : 1000
init_state_mean : [[10000], [100000], [0], [0], [0], [0]]
init_state_covariance_scaling : 1

# train method
learning_rate : 0.00001
batch_size : 32
optimizer_name: Adam
backward_sequence_length : 150

# save checkpoints
save_every_epoch : 10

# dataset
dataset:
  train : 'data/processed/train_3800.pt'